# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [2]:
import numpy as np
arr = np.random.randint(0,20, size = (4,7))
normal_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr)) 
print(f'Массив arr:\n {arr}; \nНормальзованный массив arr:\n {normal_arr}')

Массив arr:
 [[13 12 16 19 18 11  2]
 [13  7  2 19 15 16 10]
 [ 9  2  3 14 18 11  1]
 [ 4 19 16 15 19 14  3]]; 
Нормальзованный массив arr:
 [[0.66666667 0.61111111 0.83333333 1.         0.94444444 0.55555556
  0.05555556]
 [0.66666667 0.33333333 0.05555556 1.         0.77777778 0.83333333
  0.5       ]
 [0.44444444 0.05555556 0.11111111 0.72222222 0.94444444 0.55555556
  0.        ]
 [0.16666667 1.         0.83333333 0.77777778 1.         0.72222222
  0.11111111]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [37]:
mat_1=np.random.randint(0, 10, size=(8,10))
lst=[]
for i in mat_1:
    for j in range(0,mat_1.shape[0]):
        if np.sum(i) - np.sum(mat_1[j]) <= 0 and np.sum(i) - np.sum(mat_1[j-1]) < 0 and np.sum(i) - np.sum(mat_1[j-2]) < 0 and np.sum(i) - np.sum(mat_1[j-3]) < 0 and np.sum(i) - np.sum(mat_1[j-4]) < 0 and np.sum(i) - np.sum(mat_1[j-5]) < 0 and np.sum(i) - np.sum(mat_1[j-6]) < 0and np.sum(i) - np.sum(mat_1[j-7]) < 0:
            lst.append(i)
            print(f'Строка,в которой сумма значений минимальна: {lst};\nЕе индекс: {j}')     
print(f'Матрица: \n{mat_1}')

Строка,в которой сумма значений минимальна: [array([1, 0, 0, 7, 0, 0, 8, 1, 0, 6])];
Ее индекс: 5
Матрица: 
[[7 7 5 0 6 9 0 0 8 0]
 [2 4 9 1 7 8 9 1 5 8]
 [0 3 1 4 6 7 9 8 6 2]
 [5 9 5 0 6 9 3 9 0 2]
 [5 7 6 5 7 7 1 6 2 4]
 [1 0 0 7 0 0 8 1 0 6]
 [4 4 4 4 4 7 6 7 3 7]
 [6 8 6 5 7 7 5 5 8 7]]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [38]:
v_1=np.random.randint(0, 5, size=(3))
v_2=np.random.randint(0, 5, size=(3))
res_1=np.sqrt(np.sum(np.square(v_1 - v_2)))
print(f'Первый ветктор:{v_1}\nВторой ветктор:{v_2}\nЕвклидово расстояние:{res_1}')

Первый ветктор:[3 4 2]
Второй ветктор:[4 4 3]
Евклидово расстояние:1.4142135623730951


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [39]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]).reshape(3,3)
B = np.array([[3, -1], [2, 1]]).reshape(2,2)
C = np.array([[7, 21], [11, 8], [8, 4]]).reshape(3,2)
A = np.linalg.inv(A) #обратная матрица A
B = np.linalg.inv(B) #обратная матрица B
C = -C 
X = np.dot(A, C)
X = np.dot(X, B)
X

array([[ 1.00000000e+00,  1.02140518e-15],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
import numpy as np
ar_1 = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', dtype=str)
ar_2 = np.array((ar_1[1:]),dtype = np.int32)
ar_t=ar_2.copy()
ar_2[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [5]:
avg_1=np.mean(ar_2[:, 1])
avg_2=np.mean(ar_2[:, 2])
min_1=np.min(ar_2[:, 1])
min_2=np.min(ar_2[:, 2])
max_1=np.max(ar_2[:, 1])
max_2=np.max(ar_2[:, 2])
med_1=np.median(ar_2[:, 1])
med_2=np.median(ar_2[:, 2])
print(f'Средние значения: {avg_1, avg_2}, минимумы: {min_1, min_2}, максимумы: {max_1, max_2} и медианы: {med_1, med_2}')

Средние значения: (21601.00169, 9.05528), минимумы: (0, 1), максимумы: (2147483647, 39) и медианы: (40.0, 9.0)


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [6]:
q=0.75
ar_lim=ar_t[ar_t[:,1]<=np.quantile(ar_2[:,1], q)]
ar_lim

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [ 43407,     35,      7],
       [498432,     65,     15],
       [370915,      5,      4]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [7]:
num=(ar_2[:,1]==0).sum()
ar_3=np.place(ar_t[:,1], ar_t[:,1] == 0, 1)
print(f'Минимальое продолжительность рецепта измененного массива: {np.min(ar_t)}, Коливчество рецептов равных нулю: {num}')

Минимальое продолжительность рецепта измененного массива: 1, Коливчество рецептов равных нулю: 479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [8]:
print(len(np.unique(ar_1[:,0])))

100001


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [9]:
print(f'Количество различных значений ингредиентов: {len(np.unique(ar_t[:,2]))}')
print(np.unique(ar_t[:,2]))

Количество различных значений ингредиентов: 37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [10]:
print(ar_t[ar_t[:,2] <= 5])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [11]:
ar_4 = ar_t[:, 2] / ar_t[:, 1]
print(f'Максимальное значение: {np.max(ar_4)}\n{ar_4}')

Максимальное значение: 24.0
[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [13]:
ar_9 = ar_t[np.argsort(ar_t[:, 1])][-100:, 2]
print(np.average(ar_9))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [14]:
print(ar_t[np.random.randint(ar_t.shape[0], size = 10)])

[[119975    380      5]
 [343292      8      5]
 [362108    120     10]
 [416980    305     11]
 [152240     10      9]
 [295856     55     20]
 [273108     35     10]
 [286027     30      9]
 [162470     70     13]
 [136860     40     12]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [15]:
p_1 = np.mean(ar_t[:,2])
ar_10 = ar_t[ar_t[:,2]<p_1]
res_1=len(ar_10[:,2])/len(ar_t[:,2])
res_1*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [16]:
ar_cond=(ar_t[:,1] <= 20) & (ar_t[:,2] <= 5)
ar_simp=ar_t[ar_t[:,1]<=20]
ar_simp_1=ar_simp[ar_simp[:,2]<=5]
ar_add=np.hstack((ar_t, ar_cond[:, np.newaxis]))
ar_add

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [17]:
print(len(ar_simp_1)*100/len(ar_t))

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [7]:
ar_short=ar_t[ar_t[:,1]<=10]
ar_norm_0=ar_t[ar_t[:,1]>10]
ar_norm=ar_norm_0[ar_norm_0[:,1]<=20]
ar_long=ar_t[ar_t[:,1]>20]
#номера группы в трехмерном массиве ar_fin: ar_short - 0; ar_norm - 1; ar_long - 2.
ar_fin=np.arange(149592).reshape(3,12466,4)
ar_fin[0][:,1:]=ar_short[:12466,:]
ar_fin[0][:,0]=0
ar_fin[1][:,1:]=ar_norm[:12466,:]
ar_fin[1][:,0]=1
ar_fin[2][:,1:]=ar_long[:12466,:]
ar_fin[2][:,0]=2
#в трехмерном массивне  представлено по 12466 рецептов из каждой группы, из-за того, что массив numpy должен быть прямоугольным, а длина наименьшего массива ar_short составляет 12466.
ar_fin

array([[[     0,  94746,     10,      6],
        [     0,  67660,      5,      6],
        [     0, 366174,      7,      9],
        ...,
        [     0, 420725,      5,      3],
        [     0,   4747,      0,      9],
        [     0, 370915,      5,      4]],

       [[     1,  33941,     18,      9],
        [     1, 446597,     15,      5],
        [     1,  74205,     20,      7],
        ...,
        [     1, 230115,     20,      7],
        [     1, 496131,     20,      9],
        [     1, 365818,     20,      6]],

       [[     2, 127244,     60,     16],
        [     2,  23891,     25,      7],
        [     2, 157911,     60,     14],
        ...,
        [     2,  68428,     70,     10],
        [     2, 312995,   1445,      7],
        [     2,  93651,    240,     12]]])

In [8]:
len(ar_norm),len(ar_long),len(ar_short)

(14184, 73350, 12466)